# Generated by Django 5.2.3 on 2025-07-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supplier_type', models.CharField(choices=[('wholesaler', 'Atacado'), ('producer', 'Produtor'), ('other', 'Outros')], max_length=30)),
            ],
        ),
    ]
