# Generated by Django 5.2.3 on 2025-06-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.CharField(choices=[('fair', 'Feira'), ('store', 'Comércio')], max_length=10)),
            ],
        ),
    ]
