# Generated by Django 5.2.3 on 2025-06-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12),
        ),
    ]
