# Generated by Django 5.2.3 on 2025-06-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_options_alter_saleitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='custom_receipt_upload_path/'),
        ),
    ]
