# Generated by Django 5.2.3 on 2025-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_receipt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='receipt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sales_receipts/'),
        ),
    ]
